//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Store.Web.StoreWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Compras", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Compras : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProdutoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuantityIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ClientId {
            get {
                return this.ClientIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientIdField, value) != true)) {
                    this.ClientIdField = value;
                    this.RaisePropertyChanged("ClientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ProdutoId {
            get {
                return this.ProdutoIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ProdutoIdField, value) != true)) {
                    this.ProdutoIdField = value;
                    this.RaisePropertyChanged("ProdutoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string QuantityId {
            get {
                return this.QuantityIdField;
            }
            set {
                if ((object.ReferenceEquals(this.QuantityIdField, value) != true)) {
                    this.QuantityIdField = value;
                    this.RaisePropertyChanged("QuantityId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StoreWS.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Example", ReplyAction="*")]
        void Example();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Example", ReplyAction="*")]
        System.Threading.Tasks.Task ExampleAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaPedidos", ReplyAction="*")]
        void ListaPedidos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListaPedidos", ReplyAction="*")]
        System.Threading.Tasks.Task ListaPedidosAsync();
        
        // CODEGEN: Generating message contract since element name Itens from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImportarListaItens", ReplyAction="*")]
        Store.Web.StoreWS.ImportarListaItensResponse ImportarListaItens(Store.Web.StoreWS.ImportarListaItensRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ImportarListaItens", ReplyAction="*")]
        System.Threading.Tasks.Task<Store.Web.StoreWS.ImportarListaItensResponse> ImportarListaItensAsync(Store.Web.StoreWS.ImportarListaItensRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ImportarListaItensRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ImportarListaItens", Namespace="http://tempuri.org/", Order=0)]
        public Store.Web.StoreWS.ImportarListaItensRequestBody Body;
        
        public ImportarListaItensRequest() {
        }
        
        public ImportarListaItensRequest(Store.Web.StoreWS.ImportarListaItensRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ImportarListaItensRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Store.Web.StoreWS.Compras[] Itens;
        
        public ImportarListaItensRequestBody() {
        }
        
        public ImportarListaItensRequestBody(Store.Web.StoreWS.Compras[] Itens) {
            this.Itens = Itens;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ImportarListaItensResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ImportarListaItensResponse", Namespace="http://tempuri.org/", Order=0)]
        public Store.Web.StoreWS.ImportarListaItensResponseBody Body;
        
        public ImportarListaItensResponse() {
        }
        
        public ImportarListaItensResponse(Store.Web.StoreWS.ImportarListaItensResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ImportarListaItensResponseBody {
        
        public ImportarListaItensResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : Store.Web.StoreWS.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<Store.Web.StoreWS.ServiceSoap>, Store.Web.StoreWS.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Example() {
            base.Channel.Example();
        }
        
        public System.Threading.Tasks.Task ExampleAsync() {
            return base.Channel.ExampleAsync();
        }
        
        public void ListaPedidos() {
            base.Channel.ListaPedidos();
        }
        
        public System.Threading.Tasks.Task ListaPedidosAsync() {
            return base.Channel.ListaPedidosAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Store.Web.StoreWS.ImportarListaItensResponse Store.Web.StoreWS.ServiceSoap.ImportarListaItens(Store.Web.StoreWS.ImportarListaItensRequest request) {
            return base.Channel.ImportarListaItens(request);
        }
        
        public void ImportarListaItens(Store.Web.StoreWS.Compras[] Itens) {
            Store.Web.StoreWS.ImportarListaItensRequest inValue = new Store.Web.StoreWS.ImportarListaItensRequest();
            inValue.Body = new Store.Web.StoreWS.ImportarListaItensRequestBody();
            inValue.Body.Itens = Itens;
            Store.Web.StoreWS.ImportarListaItensResponse retVal = ((Store.Web.StoreWS.ServiceSoap)(this)).ImportarListaItens(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Store.Web.StoreWS.ImportarListaItensResponse> Store.Web.StoreWS.ServiceSoap.ImportarListaItensAsync(Store.Web.StoreWS.ImportarListaItensRequest request) {
            return base.Channel.ImportarListaItensAsync(request);
        }
        
        public System.Threading.Tasks.Task<Store.Web.StoreWS.ImportarListaItensResponse> ImportarListaItensAsync(Store.Web.StoreWS.Compras[] Itens) {
            Store.Web.StoreWS.ImportarListaItensRequest inValue = new Store.Web.StoreWS.ImportarListaItensRequest();
            inValue.Body = new Store.Web.StoreWS.ImportarListaItensRequestBody();
            inValue.Body.Itens = Itens;
            return ((Store.Web.StoreWS.ServiceSoap)(this)).ImportarListaItensAsync(inValue);
        }
    }
}
